spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
server.port=${PORT:8080}
server.address=${SERVER_ADDRESS:127.0.0.1}
server.forward-headers-strategy=framework
