CREATE TABLE cash_register(id SMALLINT PRIMARY KEY CHECK(id=1)); INSERT INTO cash_register VALUES(1);
CREATE TABLE expense_category(id UUID PRIMARY KEY,name VARCHAR(120) NOT NULL,active BOOLEAN NOT NULL,version BIGINT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE cash_session(id UUID PRIMARY KEY,currency VARCHAR(3) NOT NULL,opening NUMERIC(14,2) NOT NULL CHECK(opening>=0),opened_by VARCHAR(120) NOT NULL,closed_by VARCHAR(120),closed_at TIMESTAMPTZ,expected NUMERIC(14,2),counted NUMERIC(14,2) CHECK(counted>=0),difference NUMERIC(14,2),reason VARCHAR(500) NOT NULL,version BIGINT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE money_movement(id UUID PRIMARY KEY,patient_id UUID REFERENCES patient(id),original_id UUID REFERENCES money_movement(id),cash_session_id UUID REFERENCES cash_session(id),category_id UUID REFERENCES expense_category(id),kind VARCHAR(24) NOT NULL CHECK(kind IN('PAYMENT','REFUND','REVERSAL','EXPENSE','EXPENSE_REVERSAL')),currency VARCHAR(3) NOT NULL,amount NUMERIC(14,2) NOT NULL CHECK(amount>0),occurred_on DATE NOT NULL,method VARCHAR(24) NOT NULL CHECK(method IN('CASH','TRANSFER','CARD','OTHER')),reference VARCHAR(160) NOT NULL,description VARCHAR(300) NOT NULL,supplier VARCHAR(160) NOT NULL,actor_name VARCHAR(120) NOT NULL,category_name VARCHAR(120) NOT NULL,receipt_code VARCHAR(60) UNIQUE, CHECK((kind='PAYMENT' AND patient_id IS NOT NULL AND original_id IS NULL) OR (kind IN('REFUND','REVERSAL') AND patient_id IS NOT NULL AND original_id IS NOT NULL) OR (kind='EXPENSE' AND category_id IS NOT NULL AND patient_id IS NULL AND original_id IS NULL) OR(kind='EXPENSE_REVERSAL' AND original_id IS NOT NULL AND patient_id IS NULL)), CHECK(method<>'CASH' OR cash_session_id IS NOT NULL),version BIGINT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE finance_operation(id UUID PRIMARY KEY,request_key UUID NOT NULL UNIQUE,fingerprint VARCHAR(64) NOT NULL,action VARCHAR(32) NOT NULL,result_id UUID NOT NULL,reason VARCHAR(500) NOT NULL,actor_name VARCHAR(120) NOT NULL,version BIGINT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE money_application(id UUID PRIMARY KEY,patient_id UUID NOT NULL REFERENCES patient(id),payment_id UUID NOT NULL REFERENCES money_movement(id),charge_id UUID NOT NULL REFERENCES charge_entry(id),operation_id UUID NOT NULL REFERENCES finance_operation(id),amount NUMERIC(14,2) NOT NULL CHECK(amount<>0),version BIGINT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE installment_schedule(id UUID PRIMARY KEY,patient_id UUID NOT NULL REFERENCES patient(id),charge_id UUID NOT NULL REFERENCES charge_entry(id),total NUMERIC(14,2) NOT NULL CHECK(total>0),active BOOLEAN NOT NULL,reason VARCHAR(500) NOT NULL,actor_name VARCHAR(120) NOT NULL,version BIGINT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE installment(id UUID PRIMARY KEY,schedule_id UUID NOT NULL REFERENCES installment_schedule(id),position INTEGER NOT NULL CHECK(position>0),due_on DATE NOT NULL,amount NUMERIC(14,2) NOT NULL CHECK(amount>0),UNIQUE(schedule_id,position),version BIGINT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE financial_document(id UUID PRIMARY KEY,movement_id UUID REFERENCES money_movement(id),patient_id UUID REFERENCES patient(id),file_name VARCHAR(180) NOT NULL,media_type VARCHAR(40) NOT NULL,byte_size BIGINT NOT NULL CHECK(byte_size>0),sha256 VARCHAR(64) NOT NULL,description VARCHAR(300) NOT NULL,actor_name VARCHAR(120) NOT NULL,generated BOOLEAN NOT NULL,version BIGINT NOT NULL DEFAULT 0,created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE financial_content(id UUID PRIMARY KEY REFERENCES financial_document(id),content BYTEA NOT NULL);
CREATE UNIQUE INDEX idx_one_open_cash ON cash_session((1)) WHERE closed_at IS NULL;
CREATE UNIQUE INDEX idx_one_active_schedule ON installment_schedule(charge_id) WHERE active;
CREATE INDEX idx_money_patient ON money_movement(patient_id,currency,created_at DESC,id);
CREATE INDEX idx_money_original ON money_movement(original_id);
CREATE INDEX idx_money_cash ON money_movement(cash_session_id,method);
CREATE INDEX idx_application_payment ON money_application(payment_id);
CREATE INDEX idx_application_charge ON money_application(charge_id);
CREATE INDEX idx_financial_doc_movement ON financial_document(movement_id,created_at DESC,id);
CREATE INDEX idx_financial_doc_patient ON financial_document(patient_id,created_at DESC,id);
CREATE INDEX idx_installment_due ON installment(due_on,schedule_id,id);
CREATE TRIGGER money_movement_immutable BEFORE UPDATE OR DELETE ON money_movement FOR EACH ROW EXECUTE FUNCTION protect_clinical_original();
CREATE TRIGGER money_application_immutable BEFORE UPDATE OR DELETE ON money_application FOR EACH ROW EXECUTE FUNCTION protect_clinical_original();
CREATE TRIGGER finance_operation_immutable BEFORE UPDATE OR DELETE ON finance_operation FOR EACH ROW EXECUTE FUNCTION protect_clinical_original();
CREATE TRIGGER installment_immutable BEFORE UPDATE OR DELETE ON installment FOR EACH ROW EXECUTE FUNCTION protect_clinical_original();
CREATE TRIGGER financial_document_immutable BEFORE UPDATE OR DELETE ON financial_document FOR EACH ROW EXECUTE FUNCTION protect_clinical_original();
CREATE TRIGGER financial_content_immutable BEFORE UPDATE OR DELETE ON financial_content FOR EACH ROW EXECUTE FUNCTION protect_clinical_original();
CREATE FUNCTION protect_closed_cash() RETURNS TRIGGER LANGUAGE plpgsql AS $$ BEGIN IF OLD.closed_at IS NOT NULL THEN RAISE EXCEPTION 'Closed cash session is immutable'; END IF; RETURN NEW; END $$;
CREATE TRIGGER cash_session_closed BEFORE UPDATE ON cash_session FOR EACH ROW EXECUTE FUNCTION protect_closed_cash();
INSERT INTO role_permission(role_code,permission) SELECT r,p FROM unnest(ARRAY['ADMIN','CASHIER']) r CROSS JOIN unnest(ARRAY['PAYMENTS_WRITE','CASH_READ','CASH_WRITE','EXPENSES_WRITE']) p ON CONFLICT DO NOTHING;
INSERT INTO role_permission VALUES('ADMIN','FINANCE_CONFIG_WRITE') ON CONFLICT DO NOTHING;
CREATE VIEW financial_charge_balance AS SELECT c.id,c.patient_id,c.description,c.currency,
c.amount+COALESCE((SELECT SUM(x.amount) FROM charge_entry x WHERE x.original_id=c.id),0) AS debt,
COALESCE((SELECT SUM(a.amount) FROM money_application a WHERE a.charge_id=c.id),0) AS applied,
c.amount+COALESCE((SELECT SUM(x.amount) FROM charge_entry x WHERE x.original_id=c.id),0)-COALESCE((SELECT SUM(a.amount) FROM money_application a WHERE a.charge_id=c.id),0) AS pending
FROM charge_entry c WHERE c.original_id IS NULL;
